version: '3.8'

services:
  nexus-db:
    image: postgres:15-alpine
    container_name: nexus-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: nexus
    ports:
      - "5432:5432"
    volumes:
      - nexus-data:/var/lib/postgresql/data

  nexus-api:
    build: .
    container_name: nexus-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: "host=nexus-db user=postgres password=nexus dbname=nexus port=5432 sslmode=disable"
    depends_on:
      - nexus-db

volumes:
  nexus-data:
