version: '3.8'

services:
  nexus-db:
    image: postgres:15-alpine
    container_name: nexus-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: nexus
    ports:
      - "5432:5432"
    volumes:
      - nexus-db-data:/var/lib/postgresql/data

  nexus-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: "host=nexus-db user=postgres password=nexus dbname=nexus port=5432 sslmode=disable"
      SMTP_HOST: "mailpit"
      SMTP_PORT: "1025"
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: "no-reply@nexus.local"
    depends_on:
      - nexus-db
      - nexus-mailpit
    volumes:
      - nexus-uploads:/root/uploads

  nexus-mailpit:
    image: axllent/mailpit:latest
    container_name: nexus-mailpit
    restart: always
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  nexus-ui:
    build:
      context: ./nexus-frontend
      dockerfile: Dockerfile
    container_name: nexus-ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - nexus-api

volumes:
  nexus-db-data:
  nexus-uploads:
